[application]
name = "RoomMates"
out_dir = "dist"
tailwind_input = "tailwind.css"
tailwind_output = "assets/dist/tailwind.css"

[web.app]

# HTML title tag content
title = "RoomMates"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.watcher]
watch_path = ["src", "assets"]

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[bundle]
identifier = "io.github.sfseeger.roommates"
publisher = "RoomMates"
icon = [
    "packages/frontend/assets/dist/app_icons/32x32.png",
    "packages/frontend/assets/dist/app_icons/128x128.png",
    "packages/frontend/assets/dist/app_icons/128x128@2x.png",
    "packages/frontend/assets/dist/app_icons/icon.icns",
    "packages/frontend/assets/dist/app_icons/icon.ico",
]

[android.app]
min_sdk_version = 30
target_sdk_version = 36
compile_sdk_version = 34
key_alias = "key0"
jks_file = "secrets/keystore.jks"
jks_password = "password"
key_password = "password"
