[package]
name = "entity"
version = "0.1.0"
edition = "2024"

[dependencies]
sea-orm = {workspace = true, features = ["macros", "with-time"]}
serde = { workspace = true, features = ["derive"] }
form_hooks = { workspace = true }
time = { workspace = true }
