[package]
name = "api"
version = "0.1.0"
edition = "2024"

[dependencies]
dioxus = { workspace = true, features = ["fullstack"] }
sea-orm = { workspace = true, features = [
    "sqlx-mysql",
    "sqlx-sqlite", # I want people to be able to choose between mysql or sqlite.
    "runtime-tokio-native-tls",
    "macros",
    "schema-sync",
    "entity-registry",
    "with-time"
], optional = true }
serde = { workspace = true }
serde_json = { workspace = true }
dotenvy = "0.15.7"
entity = { workspace = true }
anyhow = { workspace = true }
argon2 = { version = "0.5.3", features = ["std"], optional = true }
blake3 = { version = "1.8.3", optional = true }
tokio = { version = "1", features = ["full"], optional = true }
base64 = { version = "0.22.1", optional = true }
time = { workspace = true }
regex = { workspace = true }


[features]
server = ["dioxus/server", "dep:sea-orm", "dep:tokio", "dep:argon2", "dep:blake3", "dep:base64"]
