[package]
name = "frontend"
version = "0.1.0"
edition = "2024"

[dependencies]
dioxus = { workspace = true, features = ["router", "fullstack"] }
api = { workspace = true }
anyhow = { workspace = true }
entity = { workspace = true }
dioxus-free-icons = { version = "0.10.0", features = ["lucide"] }
uuid = { version = "1.19.0", features = ["js", "v4"] }
serde = { workspace = true }
form_hooks = { workspace = true }
regex = { workspace = true }
dioxus-primitives = { git = "https://github.com/DioxusLabs/components", version = "0.0.1", default-features = false }
time = { version = "0.3.46", features = ["wasm-bindgen"] }

[features]
default = ["web"]
web = ["dioxus/web"]
mobile = ["dioxus/mobile"]
desktop = ["dioxus/desktop"]
server = ["dioxus/server", "api/server"]
