[package]
name = "roommates"
version = "0.1.0"
edition = "2024"

[dependencies]
dioxus = { workspace = true, features = ["router", "fullstack"] }
api = { workspace = true }
anyhow = { workspace = true }
entity = { workspace = true }
dioxus-free-icons = { version = "0.10.0", features = ["lucide"] }
uuid = { version = "1.19.0", features = ["js", "v4"] }
serde = { workspace = true }
serde_json = { workspace = true }
form_hooks = { workspace = true }
regex = { workspace = true }
# TODO: Change to official package once Calendar API is public
dioxus-primitives = { git = "https://github.com/SFSeeger/dioxus-components", version = "0.0.1", default-features = false }
dioxus-sdk = { version = "0.7.0", features = ["time"] }
time = { workspace = true }

[features]
default = ["web"]
web = ["dioxus/web"]
mobile = ["dioxus/mobile"]
desktop = ["dioxus/desktop"]
server = ["dioxus/server", "api/server"]
