services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: roommates
      MYSQL_USER: roommates
      MYSQL_PASSWORD: roommates_password
    volumes:
      - db_data:/var/lib/mysql

  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace
      - ~/.gitconfig:/vscode/.gitconfig
    environment:
      - TZ=Europe/Berlin
    command: sleep infinity


volumes:
  db_data:
